import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {

        new File("aaa");

        return true;
    }
}
