package sample.gradle.multi.app;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    private final Logger logger = LogManager.getLogger(Library.class);

    public boolean someLibraryMethod() {

        String hoge = null;

        if (hoge == null) {

            if (hoge == null) {
                logger.info("SpotBugs検知");
            }
        }

        // TODO:ToDo
        // FIXME:バグ対応が必要
        // XXX:基本的には不具合だが、正常ケースで問題が起きないモノ
        System.out.println("TaskScannerで検知");

        // PMDで検知されるコード
        if (true) {

        }

        logger.info("App開始");

        return true;
    }
}
